# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - /base_3dgut.yaml
  - /dataset: nerf_with_mask
  - /initialization: random
  - _self_

# overwrite of default parameters
val_frequency: 999999 # never validate

model:
  background:
    color: black 